# Form implementation generated from reading ui file 'abormalActionDetection.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 350)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video = QtWidgets.QLabel(parent=self.centralwidget)
        self.video.setGeometry(QtCore.QRect(15, 38, 256, 192))
        self.video.setObjectName("video")
        self.output = QtWidgets.QLabel(parent=self.centralwidget)
        self.output.setGeometry(QtCore.QRect(301, 38, 256, 192))
        self.output.setObjectName("output")
        self.importButtonn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.importButtonn.setGeometry(QtCore.QRect(15, 260, 113, 32))
        self.importButtonn.setObjectName("importButtonn")
        self.pathLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pathLine.setGeometry(QtCore.QRect(143, 260, 421, 32))
        self.pathLine.setReadOnly(True)
        self.pathLine.setObjectName("pathLine")
        self.videoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(15, 15, 60, 16))
        self.videoLabel.setObjectName("videoLabel")
        self.outputLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(301, 15, 60, 16))
        self.outputLabel.setObjectName("outputLabel")
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(450, 307, 113, 32))
        self.startButton.setObjectName("startButton")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(185, 307, 250, 32))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Abnormal Action Detection"))
        self.video.setText(_translate("MainWindow", "TextLabel"))
        self.output.setText(_translate("MainWindow", "TextLabel"))
        self.importButtonn.setText(_translate("MainWindow", "Import Video"))
        self.pathLine.setText(_translate("MainWindow", " "))
        self.videoLabel.setText(_translate("MainWindow", "Video:"))
        self.outputLabel.setText(_translate("MainWindow", "Output:"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Unsupervised"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Weakly Supervised"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Deep Supervised"))
