# Form implementation generated from reading ui file 'inference_view.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InferenceWindow(object):
    def setupUi(self, InferenceWindow):
        InferenceWindow.setObjectName("InferenceWindow")
        InferenceWindow.resize(1200, 800)
        self.centralWidget = QtWidgets.QWidget(parent=InferenceWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.backgroundFrame = QtWidgets.QFrame(parent=self.centralWidget)
        self.backgroundFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.backgroundFrame)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(12)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.leftFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.leftFrame)
        self.verticalLayout_12.setContentsMargins(-1, 24, -1, 24)
        self.verticalLayout_12.setSpacing(36)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.menuFrame = QtWidgets.QFrame(parent=self.leftFrame)
        self.menuFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuFrame.setObjectName("menuFrame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.menuFrame)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.menuList = QtWidgets.QListWidget(parent=self.menuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuList.sizePolicy().hasHeightForWidth())
        self.menuList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.menuList.setFont(font)
        self.menuList.setStyleSheet("QListView {\n"
"\n"
"}\n"
"QListView::item{\n"
"background-color: transparent;\n"
"    color: black;\n"
"padding:8px;\n"
"padding-left:4px;\n"
"margin-bottom:8px;\n"
"}\n"
"QListView::item:hover {\n"
"border-radius:8px;\n"
"    background-color: rgb(240, 240, 240)\n"
"\n"
"}\n"
"QListView::item:selected {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}\n"
"")
        self.menuList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.menuList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.menuList.setObjectName("menuList")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./src/resources/button/首页_home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon)
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./src/resources/button/设置_setting-two.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon1)
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./src/resources/button/导出_export.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon2)
        self.menuList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./src/resources/button/终端_terminal.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon3)
        self.menuList.addItem(item)
        self.horizontalLayout_15.addWidget(self.menuList)
        self.verticalLayout_12.addWidget(self.menuFrame)
        self.exitButton = QtWidgets.QPushButton(parent=self.leftFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton {\n"
"color: b;\n"
"border:none;\n"
"text-align:left;\n"
"padding:12px;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(239, 239, 239);\n"
"color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"padding:12px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./src/resources/button/退出_logout.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exitButton.setIcon(icon4)
        self.exitButton.setIconSize(QtCore.QSize(20, 20))
        self.exitButton.setAutoDefault(False)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout_12.addWidget(self.exitButton)
        self.verticalLayout_12.setStretch(0, 2)
        self.horizontalLayout_18.addWidget(self.leftFrame)
        self.rightFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.rightFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(237, 235, 235);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.rightFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.rightFrame)
        self.verticalLayout_13.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_13.setSpacing(12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.rightFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.homePage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ioLayout = QtWidgets.QHBoxLayout()
        self.ioLayout.setContentsMargins(12, -1, 12, -1)
        self.ioLayout.setSpacing(12)
        self.ioLayout.setObjectName("ioLayout")
        self.videoFrame = QtWidgets.QFrame(parent=self.homePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoFrame.sizePolicy().hasHeightForWidth())
        self.videoFrame.setSizePolicy(sizePolicy)
        self.videoFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.videoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.videoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.videoFrame.setObjectName("videoFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.videoFrame)
        self.verticalLayout_4.setContentsMargins(-1, 24, -1, 24)
        self.verticalLayout_4.setSpacing(24)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.videoView = QtWidgets.QLabel(parent=self.videoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoView.sizePolicy().hasHeightForWidth())
        self.videoView.setSizePolicy(sizePolicy)
        self.videoView.setMaximumSize(QtCore.QSize(509, 286))
        self.videoView.setStyleSheet("color: b;")
        self.videoView.setText("")
        self.videoView.setScaledContents(True)
        self.videoView.setObjectName("videoView")
        self.verticalLayout_4.addWidget(self.videoView)
        self.ioLayout.addWidget(self.videoFrame)
        self.showResultFrame = QtWidgets.QFrame(parent=self.homePage)
        self.showResultFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.showResultFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.showResultFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.showResultFrame.setObjectName("showResultFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.showResultFrame)
        self.verticalLayout_3.setContentsMargins(18, 12, 18, 24)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.showResultLabel = QtWidgets.QLabel(parent=self.showResultFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showResultLabel.sizePolicy().hasHeightForWidth())
        self.showResultLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        self.showResultLabel.setFont(font)
        self.showResultLabel.setStyleSheet("color: b;")
        self.showResultLabel.setObjectName("showResultLabel")
        self.verticalLayout_3.addWidget(self.showResultLabel)
        self.showResultLayout = QtWidgets.QHBoxLayout()
        self.showResultLayout.setSpacing(8)
        self.showResultLayout.setObjectName("showResultLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.showResultFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("color: b;")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.showResultLayout.addWidget(self.tableWidget)
        self.verticalLayout_3.addLayout(self.showResultLayout)
        self.ioLayout.addWidget(self.showResultFrame)
        self.ioLayout.setStretch(0, 2)
        self.verticalLayout_5.addLayout(self.ioLayout)
        self.inferenceFrame = QtWidgets.QFrame(parent=self.homePage)
        self.inferenceFrame.setStyleSheet("")
        self.inferenceFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.inferenceFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.inferenceFrame.setObjectName("inferenceFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inferenceFrame)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inferenceBackground = QtWidgets.QFrame(parent=self.inferenceFrame)
        self.inferenceBackground.setStyleSheet("QFrame{\n"
"    background-color: rgb(214, 214, 214);\n"
"border:0px solid red;\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:30px\n"
"}")
        self.inferenceBackground.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.inferenceBackground.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.inferenceBackground.setObjectName("inferenceBackground")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.inferenceBackground)
        self.horizontalLayout_13.setContentsMargins(12, -1, 12, -1)
        self.horizontalLayout_13.setSpacing(12)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.buttonLayout = QtWidgets.QVBoxLayout()
        self.buttonLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.buttonLayout.setContentsMargins(10, 20, 10, 130)
        self.buttonLayout.setSpacing(0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.importButton = QtWidgets.QPushButton(parent=self.inferenceBackground)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importButton.sizePolicy().hasHeightForWidth())
        self.importButton.setSizePolicy(sizePolicy)
        self.importButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.importButton.setFont(font)
        self.importButton.setStyleSheet("QPushButton {\n"
"border-radius:8px;\n"
"background-color: rgba(239, 239, 239, 80)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}")
        self.importButton.setObjectName("importButton")
        self.buttonLayout.addWidget(self.importButton)
        self.startButton = QtWidgets.QPushButton(parent=self.inferenceBackground)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("QPushButton {\n"
"border-radius:8px;\n"
"background-color: rgba(239, 239, 239, 80)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.buttonLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.inferenceBackground)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stopButton.setFont(font)
        self.stopButton.setStyleSheet("QPushButton {\n"
"border-radius:8px;\n"
"background-color: rgba(239, 239, 239, 80)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}")
        self.stopButton.setObjectName("stopButton")
        self.buttonLayout.addWidget(self.stopButton)
        self.horizontalLayout_13.addLayout(self.buttonLayout)
        self.inputFrame = QtWidgets.QFrame(parent=self.inferenceBackground)
        self.inputFrame.setMinimumSize(QtCore.QSize(350, 300))
        self.inputFrame.setMaximumSize(QtCore.QSize(350, 300))
        self.inputFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.inputFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.inputFrame.setObjectName("inputFrame")
        self.inputIcon = QtWidgets.QFrame(parent=self.inputFrame)
        self.inputIcon.setGeometry(QtCore.QRect(19, 4, 40, 41))
        self.inputIcon.setStyleSheet("QFrame{\n"
"padding:8px;\n"
"image: url(\"./src/resources/button_white/传入_afferent.svg\");\n"
"background-color: rgb(255, 81, 45);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.inputIcon.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.inputIcon.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.inputIcon.setObjectName("inputIcon")
        self.inputBackground = QtWidgets.QFrame(parent=self.inputFrame)
        self.inputBackground.setGeometry(QtCore.QRect(5, 26, 341, 261))
        self.inputBackground.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.inputBackground.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.inputBackground.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.inputBackground.setObjectName("inputBackground")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.inputBackground)
        self.verticalLayout_7.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.inputImg = QtWidgets.QLabel(parent=self.inputBackground)
        self.inputImg.setMaximumSize(QtCore.QSize(317, 178))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.inputImg.setFont(font)
        self.inputImg.setScaledContents(True)
        self.inputImg.setObjectName("inputImg")
        self.verticalLayout_7.addWidget(self.inputImg)
        self.inputBackground.raise_()
        self.inputIcon.raise_()
        self.horizontalLayout_13.addWidget(self.inputFrame)
        self.resultFrame = QtWidgets.QFrame(parent=self.inferenceBackground)
        self.resultFrame.setMinimumSize(QtCore.QSize(350, 300))
        self.resultFrame.setMaximumSize(QtCore.QSize(350, 300))
        self.resultFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultFrame.setObjectName("resultFrame")
        self.resultIcon = QtWidgets.QFrame(parent=self.resultFrame)
        self.resultIcon.setGeometry(QtCore.QRect(19, 4, 40, 41))
        self.resultIcon.setStyleSheet("QFrame{\n"
"padding:8px;\n"
"image: url(\"./src/resources/button_white/差异集_difference-set.svg\");\n"
"background-color: rgb(255, 81, 45);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.resultIcon.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultIcon.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultIcon.setObjectName("resultIcon")
        self.resultBackground = QtWidgets.QFrame(parent=self.resultFrame)
        self.resultBackground.setGeometry(QtCore.QRect(5, 26, 341, 261))
        self.resultBackground.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.resultBackground.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.resultBackground.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.resultBackground.setObjectName("resultBackground")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.resultBackground)
        self.verticalLayout_8.setContentsMargins(-1, 24, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.resultImg = QtWidgets.QLabel(parent=self.resultBackground)
        self.resultImg.setMaximumSize(QtCore.QSize(317, 178))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.resultImg.setFont(font)
        self.resultImg.setScaledContents(True)
        self.resultImg.setObjectName("resultImg")
        self.verticalLayout_8.addWidget(self.resultImg)
        self.resultBackground.raise_()
        self.resultIcon.raise_()
        self.horizontalLayout_13.addWidget(self.resultFrame)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(2, 1)
        self.verticalLayout.addWidget(self.inferenceBackground)
        self.verticalLayout_5.addWidget(self.inferenceFrame)
        self.stackedWidget.addWidget(self.homePage)
        self.settingPage = QtWidgets.QWidget()
        self.settingPage.setObjectName("settingPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.settingPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.settingFrame = QtWidgets.QFrame(parent=self.settingPage)
        self.settingFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.settingFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.settingFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.settingFrame.setObjectName("settingFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.settingFrame)
        self.verticalLayout_6.setContentsMargins(-1, 24, -1, 24)
        self.verticalLayout_6.setSpacing(24)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.inputDeviceBox = QtWidgets.QGroupBox(parent=self.settingFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.inputDeviceBox.setFont(font)
        self.inputDeviceBox.setStyleSheet("")
        self.inputDeviceBox.setObjectName("inputDeviceBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.inputDeviceBox)
        self.horizontalLayout.setContentsMargins(24, -1, 24, -1)
        self.horizontalLayout.setSpacing(24)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.videoSettingLabel = QtWidgets.QLabel(parent=self.inputDeviceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoSettingLabel.sizePolicy().hasHeightForWidth())
        self.videoSettingLabel.setSizePolicy(sizePolicy)
        self.videoSettingLabel.setMinimumSize(QtCore.QSize(305, 0))
        self.videoSettingLabel.setMaximumSize(QtCore.QSize(305, 172))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.videoSettingLabel.setFont(font)
        self.videoSettingLabel.setStyleSheet("color:b")
        self.videoSettingLabel.setObjectName("videoSettingLabel")
        self.horizontalLayout.addWidget(self.videoSettingLabel)
        self.deviceLabel = QtWidgets.QLabel(parent=self.inputDeviceBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.deviceLabel.setFont(font)
        self.deviceLabel.setStyleSheet("color: b; background-color: transparent;")
        self.deviceLabel.setObjectName("deviceLabel")
        self.horizontalLayout.addWidget(self.deviceLabel)
        self.deviceLine = QtWidgets.QLineEdit(parent=self.inputDeviceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceLine.sizePolicy().hasHeightForWidth())
        self.deviceLine.setSizePolicy(sizePolicy)
        self.deviceLine.setMinimumSize(QtCore.QSize(250, 0))
        self.deviceLine.setObjectName("deviceLine")
        self.horizontalLayout.addWidget(self.deviceLine)
        self.deviceButton = QtWidgets.QPushButton(parent=self.inputDeviceBox)
        self.deviceButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.deviceButton.setFont(font)
        self.deviceButton.setStyleSheet("QPushButton {\n"
"border-radius:8px;\n"
"background-color: rgba(239, 239, 239, 80)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}")
        self.deviceButton.setObjectName("deviceButton")
        self.horizontalLayout.addWidget(self.deviceButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.inputDeviceBox)
        self.inferenceBox = QtWidgets.QGroupBox(parent=self.settingFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.inferenceBox.setFont(font)
        self.inferenceBox.setStyleSheet("back")
        self.inferenceBox.setObjectName("inferenceBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.inferenceBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.inferenceLayout = QtWidgets.QHBoxLayout()
        self.inferenceLayout.setObjectName("inferenceLayout")
        self.inferenceLabel = QtWidgets.QLabel(parent=self.inferenceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inferenceLabel.sizePolicy().hasHeightForWidth())
        self.inferenceLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inferenceLabel.setFont(font)
        self.inferenceLabel.setStyleSheet("color: b; background-color:transparent;")
        self.inferenceLabel.setObjectName("inferenceLabel")
        self.inferenceLayout.addWidget(self.inferenceLabel)
        self.inferenceLine = QtWidgets.QLineEdit(parent=self.inferenceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inferenceLine.sizePolicy().hasHeightForWidth())
        self.inferenceLine.setSizePolicy(sizePolicy)
        self.inferenceLine.setMinimumSize(QtCore.QSize(250, 0))
        self.inferenceLine.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inferenceLine.setFont(font)
        self.inferenceLine.setObjectName("inferenceLine")
        self.inferenceLayout.addWidget(self.inferenceLine)
        self.inferenceRangeLabel = QtWidgets.QLabel(parent=self.inferenceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inferenceRangeLabel.sizePolicy().hasHeightForWidth())
        self.inferenceRangeLabel.setSizePolicy(sizePolicy)
        self.inferenceRangeLabel.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inferenceRangeLabel.setFont(font)
        self.inferenceRangeLabel.setStyleSheet("color: b; background-color:transparent;")
        self.inferenceRangeLabel.setObjectName("inferenceRangeLabel")
        self.inferenceLayout.addWidget(self.inferenceRangeLabel)
        self.inferenceButton = QtWidgets.QPushButton(parent=self.inferenceBox)
        self.inferenceButton.setMinimumSize(QtCore.QSize(200, 0))
        self.inferenceButton.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.inferenceButton.setFont(font)
        self.inferenceButton.setStyleSheet("QPushButton {\n"
"border-radius:8px;\n"
"background-color: rgba(239, 239, 239, 80)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}")
        self.inferenceButton.setObjectName("inferenceButton")
        self.inferenceLayout.addWidget(self.inferenceButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.inferenceLayout.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.inferenceLayout)
        self.timeIntervalLayout = QtWidgets.QHBoxLayout()
        self.timeIntervalLayout.setObjectName("timeIntervalLayout")
        self.timeIntervalLabel = QtWidgets.QLabel(parent=self.inferenceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeIntervalLabel.sizePolicy().hasHeightForWidth())
        self.timeIntervalLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timeIntervalLabel.setFont(font)
        self.timeIntervalLabel.setStyleSheet("color: b; background-color:transparent;")
        self.timeIntervalLabel.setObjectName("timeIntervalLabel")
        self.timeIntervalLayout.addWidget(self.timeIntervalLabel)
        self.timeIntervalLine = QtWidgets.QLineEdit(parent=self.inferenceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeIntervalLine.sizePolicy().hasHeightForWidth())
        self.timeIntervalLine.setSizePolicy(sizePolicy)
        self.timeIntervalLine.setMinimumSize(QtCore.QSize(250, 0))
        self.timeIntervalLine.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timeIntervalLine.setFont(font)
        self.timeIntervalLine.setObjectName("timeIntervalLine")
        self.timeIntervalLayout.addWidget(self.timeIntervalLine)
        self.timeIntervalButton = QtWidgets.QPushButton(parent=self.inferenceBox)
        self.timeIntervalButton.setMinimumSize(QtCore.QSize(200, 0))
        self.timeIntervalButton.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.timeIntervalButton.setFont(font)
        self.timeIntervalButton.setStyleSheet("QPushButton {\n"
"border-radius:8px;\n"
"background-color: rgba(239, 239, 239, 80)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}")
        self.timeIntervalButton.setObjectName("timeIntervalButton")
        self.timeIntervalLayout.addWidget(self.timeIntervalButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.timeIntervalLayout.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.timeIntervalLayout)
        self.resultExportLayout = QtWidgets.QHBoxLayout()
        self.resultExportLayout.setObjectName("resultExportLayout")
        self.resultExportLabel = QtWidgets.QLabel(parent=self.inferenceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultExportLabel.sizePolicy().hasHeightForWidth())
        self.resultExportLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resultExportLabel.setFont(font)
        self.resultExportLabel.setStyleSheet("color: b; background-color:transparent;")
        self.resultExportLabel.setObjectName("resultExportLabel")
        self.resultExportLayout.addWidget(self.resultExportLabel)
        self.resultExportLine = QtWidgets.QLineEdit(parent=self.inferenceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultExportLine.sizePolicy().hasHeightForWidth())
        self.resultExportLine.setSizePolicy(sizePolicy)
        self.resultExportLine.setMinimumSize(QtCore.QSize(400, 0))
        self.resultExportLine.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resultExportLine.setFont(font)
        self.resultExportLine.setObjectName("resultExportLine")
        self.resultExportLayout.addWidget(self.resultExportLine)
        self.resultExportFile = QtWidgets.QPushButton(parent=self.inferenceBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultExportFile.sizePolicy().hasHeightForWidth())
        self.resultExportFile.setSizePolicy(sizePolicy)
        self.resultExportFile.setMinimumSize(QtCore.QSize(200, 0))
        self.resultExportFile.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resultExportFile.setFont(font)
        self.resultExportFile.setStyleSheet("QPushButton {\n"
"border-radius:8px;\n"
"background-color: rgba(239, 239, 239, 80)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(12, 20, 36);\n"
"border-radius:8px;\n"
"}")
        self.resultExportFile.setObjectName("resultExportFile")
        self.resultExportLayout.addWidget(self.resultExportFile)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.resultExportLayout.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.resultExportLayout)
        self.verticalLayout_6.addWidget(self.inferenceBox)
        self.stopCondBox = QtWidgets.QGroupBox(parent=self.settingFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.stopCondBox.setFont(font)
        self.stopCondBox.setObjectName("stopCondBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.stopCondBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stopCondComboBox = QtWidgets.QComboBox(parent=self.stopCondBox)
        self.stopCondComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.stopCondComboBox.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stopCondComboBox.setFont(font)
        self.stopCondComboBox.setStyleSheet("color: b;")
        self.stopCondComboBox.setObjectName("stopCondComboBox")
        self.horizontalLayout_2.addWidget(self.stopCondComboBox)
        self.verticalLayout_6.addWidget(self.stopCondBox)
        self.verticalLayout_9.addWidget(self.settingFrame)
        self.stackedWidget.addWidget(self.settingPage)
        self.consolePage = QtWidgets.QWidget()
        self.consolePage.setObjectName("consolePage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.consolePage)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.consoleFrame = QtWidgets.QFrame(parent=self.consolePage)
        self.consoleFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"    color: rgb(255, 254, 255);\n"
"border-radius:30px\n"
"}")
        self.consoleFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.consoleFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.consoleFrame.setObjectName("consoleFrame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.consoleFrame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.consoleText = QtWidgets.QTextEdit(parent=self.consoleFrame)
        self.consoleText.setObjectName("consoleText")
        self.verticalLayout_14.addWidget(self.consoleText)
        self.verticalLayout_11.addWidget(self.consoleFrame)
        self.stackedWidget.addWidget(self.consolePage)
        self.verticalLayout_13.addWidget(self.stackedWidget)
        self.horizontalLayout_18.addWidget(self.rightFrame)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 5)
        self.verticalLayout_2.addWidget(self.backgroundFrame)
        InferenceWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(InferenceWindow)
        self.menuList.setCurrentRow(-1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(InferenceWindow)

    def retranslateUi(self, InferenceWindow):
        _translate = QtCore.QCoreApplication.translate
        InferenceWindow.setWindowTitle(_translate("InferenceWindow", "自动化判级 - Yolo v5"))
        __sortingEnabled = self.menuList.isSortingEnabled()
        self.menuList.setSortingEnabled(False)
        item = self.menuList.item(0)
        item.setText(_translate("InferenceWindow", "主页"))
        item = self.menuList.item(1)
        item.setText(_translate("InferenceWindow", "设置"))
        item = self.menuList.item(2)
        item.setText(_translate("InferenceWindow", "结果导出"))
        item = self.menuList.item(3)
        item.setText(_translate("InferenceWindow", "控制台输出"))
        self.menuList.setSortingEnabled(__sortingEnabled)
        self.exitButton.setText(_translate("InferenceWindow", "退 出"))
        self.showResultLabel.setText(_translate("InferenceWindow", "结果"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("InferenceWindow", "名字"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("InferenceWindow", "数量"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("InferenceWindow", "平均分 (%)"))
        self.importButton.setText(_translate("InferenceWindow", "分析本地图片"))
        self.startButton.setText(_translate("InferenceWindow", "开  始"))
        self.stopButton.setText(_translate("InferenceWindow", "停  止"))
        self.inputImg.setText(_translate("InferenceWindow", "Input"))
        self.resultImg.setText(_translate("InferenceWindow", "Result"))
        self.inputDeviceBox.setTitle(_translate("InferenceWindow", "视频输入设备"))
        self.videoSettingLabel.setText(_translate("InferenceWindow", "VideoInputDevice"))
        self.deviceLabel.setText(_translate("InferenceWindow", "摄像头地址："))
        self.deviceButton.setText(_translate("InferenceWindow", "确定"))
        self.inferenceBox.setTitle(_translate("InferenceWindow", "识别判级参数设置"))
        self.inferenceLabel.setText(_translate("InferenceWindow", "识别比例阈值："))
        self.inferenceRangeLabel.setText(_translate("InferenceWindow", "(0~1)"))
        self.inferenceButton.setText(_translate("InferenceWindow", "确  定"))
        self.timeIntervalLabel.setText(_translate("InferenceWindow", "截图时间间隔："))
        self.timeIntervalButton.setText(_translate("InferenceWindow", "确  定"))
        self.resultExportLabel.setText(_translate("InferenceWindow", "结果导出目录："))
        self.resultExportFile.setText(_translate("InferenceWindow", "打  开"))
        self.stopCondBox.setTitle(_translate("InferenceWindow", "自动停止条件"))
